### ISSUE TITLE
Proposed Change To Overview Of Fraud Protection Features Documentation 

### ISSUE THREAD

**Issue by Sirlupinwatson1** [MicrosoftDocs/dynamics-365-fraud-protection#11]
[Hi everyone, 

I think we should modify this line here: Because the return on investment (ROI) for online fraud is high.

There is no ROI Return on Investments beside working in parallel with Fraud, we should not bring this association of the word ROI with the word Fraud from that perspective. We should have a different and more convivial approach that represent a more up-do-date daily example of what is Fraud currently. 

I will also point at this passage here: Examples include money laundering and posting fake news. (What does Fake news have in common with Fraud?) This should be removed, and as mentioned above, up-do-date comparison should be written instead.

What do you think?

Regards, Armand B. ] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f57f2f1-57c1-c9ee-3786-88f81c7b30d2
* Version Independent ID: 2a74ad26-0806-fd08-9d04-ff65117901ac
* Content: [Overview of Fraud Protection features - Dynamics 365 Fraud Protection](https://docs.microsoft.com/en-us/dynamics365/fraud-protection/overview)
* Content Source: [content/overview.md](https://github.com/MicrosoftDocs/dynamics-365-fraud-protection/blob/master/content/overview.md)
* Service: **fraud-protection**
* GitHub Login: @YvonneDeQ
* Microsoft Alias: **v-madeq**

**Comment by josaw1** [comment]
Thanks for your feedback. @YvonneDeQ can you please take a look?

**Comment by YvonneDeQ** [comment]
Fix is being reviewed by PM.

**Comment by YvonneDeQ** [comment]
@ArmandB., 
Thank you for your feedback. The PM has approved the following changes to the Overview topic.
Changing: Some types of fraud even have serious consequences for society at large. Examples include money laundering and posting fake news.
To: Some types of fraud even have serious consequences for society at large, for example, money laundering.
Changing: Because the return on investment (ROI) for online fraud is high, ...
To: Because the return on investment reaped by fraudsters by doing online fraud and abuse is high, it's likely that most of an enterprise's vulnerabilities will be discovered and exploited.
Changing: Our mission is to help enterprises fight fraud while they keep their doors open for genuine customers and partners.
To 
Our mission is to help enterprises fight fraud and abuse while they keep their doors open for genuine customers and partners.
You can review the changes in: Overview of Fraud Protection features. They will be rolled into the DFP release on 10/6.
Please let me know if you have any questions,
Yvonne

**Comment by Sirlupinwatson1** [comment]
Hi @YvonneDeQ 

I hope you are doing good! This is great, thank you very much for the support and adaptative change to the documentation. 

We all know that currently the impact of Fraud is affecting many organisation and compagnies witch result in massive amount of financial decrease in their hard winning ROI, but this can escalade quickly to different level and loss definition can be overviewed differentially since the negative side is going way further than just the Financial part.  

Going at the source as a Security advisor and Researcher within the Cloud Architecture, I have experienced multiple Fraud approach occurring lately. Recently It has become a serious problem that can affect everyone and Fraud are unfortunately present more than never in the Technology of today. 

The association of the word Fraud inside an organisation should be incorporated in the current training of each employee simply by working on the prevention reducing by at least 50% the chance of getting scammed with a phishing email for example. 

So the fraud aspect can be appointed with the source directly defined by fraudulent email or fake job offer and recruitment, too good to be true investment solution, and the list goes on. 

I really dislike fraudulent people and we will work harder to take them out. 

I wish you a very wonderful afternoon, 
Best Regards, Armand Brunelle.
